config/routes.rb
Rails.application.routes.draw do

  get 'style/new'

 root "home#new"
 resources :saloons
 resources :users

 get '/login', to: 'sessions#new'
 delete '/logout', to: 'sessions#destroy'
 resources :sessions, only: [:new, :create, :destroy]

 resources :saloons do
   member do
     get "like", to: "saloons#upvote"
   end
 end


end

app/models/saloon.rb
class Saloon < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  acts_as_votable

  has_many :barbers, class_name:'User', foreign_key:'saloon_id'

  validates :name, :description, :price, presence: true
  validates :description, length: { minimum: 5, maximum: 1000, 
    too_long: "%{count} characters is the maximum allowed"}

  end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  belongs_to :saloon, class_name: "Saloon", foreign_key: 'saloon_id'


  validates :email, presence: true, uniqueness: true
  validates :password, length: { in: 5..10 } 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authenticate
    unless logged_in?
      flash[:error] = "You must be logged_in to access this page"
      redirect_to login_url
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def new
  end
end

app/controllers/saloons_controller.rb
class SaloonsController < ApplicationController
  before_action :set_saloon, only: [:show, :edit, :update, :destroy]

  # GET /saloons
  # GET /saloons.json
  def index
    @search = Saloon.search(params[:q])
    @saloons = @search.result
    #@saloons = Saloon.all
  end

  # GET /saloons/1
  # GET /saloons/1.json
  def show
  
  end

  # GET /saloons/new
  def new
    @saloon = Saloon.new
  end

  # GET /saloons/1/edit
  def edit
  end

  # POST /saloons
  # POST /saloons.json
  def create
    @saloon = Saloon.new(saloon_params)

    respond_to do |format|
      if @saloon.save
        format.html { redirect_to @saloon, notice: 'Saloon was successfully created.' }
        format.json { render :show, status: :created, location: @saloon }
      else
        format.html { render :new }
        format.json { render json: @saloon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saloons/1
  # PATCH/PUT /saloons/1.json
  def update
    respond_to do |format|
      if @saloon.update(saloon_params)
        format.html { redirect_to @saloon, notice: 'Saloon was successfully updated.' }
        format.json { render :show, status: :ok, location: @saloon }
      else
        format.html { render :edit }
        format.json { render json: @saloon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saloons/1
  # DELETE /saloons/1.json
  def destroy
    @saloon.destroy
    respond_to do |format|
      format.html { redirect_to saloons_url, notice: 'Saloon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @saloon = Saloon.find(params[:id])
    @saloon.upvote_by current_user
    redirect_to @saloon
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saloon
      @saloon = Saloon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saloon_params
      params.require(:saloon).permit(:name, :image, :description, :tel_number, :price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def new
  end

  def create
    user = User.find_by_email(params[:email]) 
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "You're Logged in!" 
    else
      flash.now.alert = "Your Email or Password is invalid!"
      render "new"
    end
  end

  def destroy
   session[:user_id] = nil 
   redirect_to root_url, notice: "logged out!"
 end
end

app/controllers/style_controller.rb
class StyleController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  #  @users = User.like!(user_params)
  
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
   @user = User.new user_params
   if @user.save
    if @user.role == "Barber"
    redirect_to users_path, notice: "You have now registered, please log in and edit your profile!"
    else
      redirect_to users_path
    end 
   else
    render 'new'
   end
  end
  
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role, :saloon_id, :price, :availability, :description, :location, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barbers_helper.rb
module BarbersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/saloons_helper.rb
module SaloonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/style_helper.rb
module StyleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/new.html.erb
    <div class="homepage_buttons">
      <%= link_to "Find a salon", saloons_path, class: "button" %>
    </div>

    <!-- logo -->
<div class="logo">
    <%= image_tag "logo.png", width: 200 %>
    </div>

    <!-- Image slder -->
  <div class="main">
    <div class="pic_Holder">
      <section class="collection">
        <figure class="pic">
          <%= image_tag "home_image1.jpg" %> 
          <figcaption>
          Pimp this...
          </figcaption> 
        </figure>

        <figure class="pic">
          <%= image_tag "home_image4.jpg" %> 
        </figure>

        <figure class="pic">
          <%= image_tag "home_image3.jpg" %>        
          <figcaption>
           Feels greats to be pimped
          </figcaption> 
        </figure>

        
      </section>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Pimp My Style</a></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li><a href="/saloons"> Find a Saloon </a></li>
        <li><a href="style/new"> Styles </a></li>
        <% if current_user %>
        <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
        <li><%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure?"} %></li>
      <% else %>
      <li><%= link_to "Login", login_path %></li>
      <li><%= link_to "Register", new_user_path %></li>
      <% end %>
    </ul>
  </section>
</nav>

<% flash.each do |name, message| %>
<div class="flash-message flash-message-<%= name %>">
  <%= message %>
</div>
<% end %>

<%= yield %>

<div class="footer">

<ul class="social_buttons">
  <li><%= image_tag "twitter.png", width: 40 %> <li><span>
  <li><%= image_tag "GooglePlus.png", width: 40 %> <li><span>
  <li><%= image_tag "facebook.png", width: 40 %> <li>
</ul>
    <p>&copy Copyright 2015</p>
</div>
</body>


</html>

app/views/saloons/_form.html.erb
<%= form_for(@saloon) do |f| %>
<% if @saloon.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@saloon.errors.count, "error") %> prohibited this saloon from being saved:</h2>

  <ul>
    <% @saloon.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>



<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>

<div class="field">
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</div>
<div class="field">
  <%= f.label :tel_number %><br>
  <%= f.number_field :tel_number %>
</div>
<div class="field">
  <%= f.label :price %><br>
  <%= f.number_field :price %>
</div>
<div class="button-radius">
  <%= f.button "Register" %></div>
<% end %>

app/views/saloons/edit.html.erb
<h1>Re-style your Shop Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @saloon %> |
<%= link_to 'Back', saloons_path %>

app/views/saloons/index.html.erb
<p id="notice"><%= notice %></p>

<%=  search_form_for @search do |f| %>
<div class="search-box">
  <%= f.label "Search for Barshops" %>
  <%= f.text_field :name_cont %>
</div>
<div class="search-button">
  <%= f.submit "search" %>
</div>
<% end %>


<h1>List of Barber Shops</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Description</th>
      <th>Tel number</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @saloons.each do |saloon| %>
      <tr>
        <td><%= saloon.name %></td>
        <td><%= image_tag (saloon.image) %></td>
        <td><%= saloon.description %></td>
        <td><%= saloon.tel_number %></td>
        <td><%= saloon.price %></td>
        <td><%= link_to 'Show', saloon %></td>
        <td><%= link_to 'Edit', edit_saloon_path(saloon) %>  </td>
        <td><%= link_to 'Destroy', saloon, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      </tr>
   <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Saloon', new_saloon_path %>

app/views/saloons/new.html.erb
<h1>New Barber Shop</h1>

<%= render 'form' %>

<%= link_to 'Back', saloons_path %>

app/views/saloons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @saloon.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @saloon.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @saloon.description %>
</p>

<p>
  <strong>Tel number:</strong>
  <%= @saloon.tel_number %>
</p>

<p>
  Image:
  <%= image_tag @saloon.image %>
  <%= link_to @saloon.image  %>
</p>

<p>
  <strong>Price:</strong>
  <%= @saloon.price %>
</p>

<p>
  <strong>Barbers:</strong>
  <ul>
  <% @saloon.barbers.each do |barber| %>
    <li><%= link_to "#{barber.first_name} #{barber.last_name}", barber  %></li>
  <% end %>
  </ul>
</p>

<h2>Likes: <%= @saloon.get_likes.size %></h2>

<% if @saloon.liked_by current_user %>
  <p>You have already Liked this saloon!</p>
<% else %>
<%= link_to "upvote", like_saloon_path(@saloon), method: :put %>
<% end %>

<%= link_to 'Edit', edit_saloon_path(@saloon) %> |
<%= link_to 'Back', saloons_path %>

app/views/style/new.html.erb
<h1>Pimped Hairstyles</h1>
<h1>Lots of Styles</h1>


<div id="pic">
  
<%= image_tag "funky1.jpg", width: 200 %>
<%= image_tag "funky2.jpg", width: 172 %>
<%= image_tag "funky3.jpg", width: 200 %>
<%= image_tag "funky4.jpg", width: 290 %>
<%= image_tag "braids1.jpg", width: 130  %>
<%= image_tag "style1.jpg", width: 200 %>
<%= image_tag "style3.jpg", width: 194 %>

<%= image_tag "style5.jpg", width: 200 %>
<%= image_tag "style6.jpg", width: 178 %>
<%= image_tag "style8.jpg", width: 170 %>
<%= image_tag "style9.jpg", width: 160 %>
<%= image_tag "style11.jpg", width: 140 %>
<%= image_tag "style4.jpg", width: 200 %>
<%= image_tag "style10.jpg", width: 200  %>
<%= image_tag "style7.jpg", width: 200 %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div><br>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div><br>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div><br>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div><br>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div><br>
  
  <% if @user.role == nil %>
  <div class="field">
    <%= f.label :role %>
    <%= f.select :role, options_for_select(["Client", "Barber"]) %>
  </div><br>
  <% end %>

  <% if @user.role == "Barber" %>
    <%= f.label :saloon_id, "Which Saloon do you belong to?" %>
    <%= f.collection_select :saloon_id, Saloon.all, :id, :name %>
    <br>
    <%= f.label :location, "Location" %>
    <%= f.select :location, options_for_select(["Camden", "City", "Croydon", "Ealing", "Enfield", "Greenwich", "Hackney", "Haringey", "Islington", "Lambeth", "Southwark", "Tower Hamlets", "Westminster"]) %>
    <br>
    <%= f.label :price, "Price" %>
    <%= f.number_field :price %>
    <br>
    <%= f.label :availability, "Availablity" %>
    <%= f.date_field :availability %>
    <br>
    <%= f.label :description, "A Little about yourself:" %>
    <%= f.text_area :description %>
    <br>
    <%= f.label :image, "Image Link:" %>
    <%= f.text_field :image %>


  <% end %><br>

  <div class="actions button">
    <%= f.submit "Get Pimped!" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Pimp your Style up! (Edit)</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Clients</h1>


<% @users.each do |user| %>
  <% if user.role == "Barber" %>
  <ul>
    <li><%= image_tag(user.image, width: 100)%></li>
    <li><%= link_to user.first_name, user %></li>
  </ul>

  <ul>
    <li><%= image_tag(user.image, width: 100)%></li>
    <li><%= link_to user.first_name, user %></li>
  </ul>
  <% end %>
<% end %>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Get Ready to be Pimped Up!</h1>
<h4>Register here to get a list of available Barbers in your location </h4>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% form_for users_path do %>
<p>
  <%= text_field_tag :search %>
  <%= submit_tag "search" %>
</p>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>


<p>
  <strong>Availability:</strong>
  <%= @user.availability %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>Price per haircut:</strong>
  £<%= @user.price %>
</p>

<% if @user.saloon_id != nil %>
<p>
  <strong>Saloon:</strong>
  <%= link_to Saloon.find(@user.saloon_id).name, Saloon.find(@user.saloon_id)  %>
</p>
<% end %>

<% if !!current_user %>
  <% if current_user.id == @user.id %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
  <% end %>
<% end %>